-- RAG layer for the AI Sherpa chatbot.
--
-- Each protocol's body_md (and patient_md) gets split by ## heading into
-- chunks. Each chunk gets an embedding generated by OpenAI
-- text-embedding-3-small (1536 dimensions). The chat API embeds the user's
-- query and retrieves the top-K nearest chunks via cosine similarity, then
-- injects them into the system prompt as grounded context.
--
-- Idempotent. Safe to re-run.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS protocol_chunks (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  protocol_id  uuid NOT NULL REFERENCES protocols(id) ON DELETE CASCADE,
  slug         text NOT NULL,
  audience     text NOT NULL CHECK (audience IN ('clinician','patient')),
  heading      text,
  chunk_text   text NOT NULL,
  embedding    vector(1536),
  chunk_order  integer NOT NULL DEFAULT 0,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_protocol_chunks_protocol_id
  ON protocol_chunks(protocol_id);

CREATE INDEX IF NOT EXISTS idx_protocol_chunks_audience
  ON protocol_chunks(audience);

-- HNSW for fast cosine similarity. Requires pgvector >= 0.5.0 (Supabase
-- ships >= 0.7.x as of mid-2025).
CREATE INDEX IF NOT EXISTS idx_protocol_chunks_embedding
  ON protocol_chunks USING hnsw (embedding vector_cosine_ops);

-- Top-K retrieval RPC. The chat API passes the user query as an embedding;
-- this returns the most semantically similar published-protocol chunks
-- restricted to the requested audience (default 'clinician' since AI Sherpa
-- is clinician-facing).
CREATE OR REPLACE FUNCTION match_protocol_chunks(
  query_embedding vector(1536),
  match_count     integer DEFAULT 5,
  target_audience text    DEFAULT 'clinician',
  min_similarity  real    DEFAULT 0.30
)
RETURNS TABLE (
  protocol_id uuid,
  slug        text,
  title       text,
  heading     text,
  chunk_text  text,
  similarity  real
)
LANGUAGE sql STABLE AS $$
  SELECT
    pc.protocol_id,
    pc.slug,
    p.title,
    pc.heading,
    pc.chunk_text,
    (1 - (pc.embedding <=> query_embedding))::real AS similarity
  FROM protocol_chunks pc
  JOIN protocols p ON p.id = pc.protocol_id
  WHERE pc.audience = target_audience
    AND p.status = 'published'
    AND pc.embedding IS NOT NULL
    AND (1 - (pc.embedding <=> query_embedding))::real > min_similarity
  ORDER BY pc.embedding <=> query_embedding
  LIMIT match_count;
$$;

-- RLS — chunks of published protocols are readable by AUTHENTICATED users
-- only. The chat API runs under the user's session, so a logged-in clinician
-- is already verified before the RPC is invoked. Anon clients must NOT be
-- able to scrape the embedding corpus.
ALTER TABLE protocol_chunks ENABLE ROW LEVEL SECURITY;

-- Drop both the old (overly broad) and new policy names so the migration is
-- re-runnable across either prior state.
DROP POLICY IF EXISTS "Anyone can read chunks of published protocols" ON protocol_chunks;
DROP POLICY IF EXISTS "Authenticated users can read chunks of published protocols" ON protocol_chunks;
CREATE POLICY "Authenticated users can read chunks of published protocols"
  ON protocol_chunks FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM protocols
      WHERE protocols.id = protocol_chunks.protocol_id
        AND protocols.status = 'published'
    )
  );
